### ISSUE TITLE
Run run_exps.py

### ISSUE THREAD

**Issue by wenxinyang1026** [LINs-lab/FedTHE#5]
Hello，thanks for your excellent work!
When I run the experiment as 'python run_exps.py --script_path exps/exp_cifar10_cnn.py' in README.md, I found that in the 'create_jobs_on_node()' function, only scripts[0] enters and executes the second 'if', so the variable 'current_degree_parallelism' is equal to 1, and then it will loop infinitely in 'while', and each loop will only execute 'time.sleep()'. That makes me confused and want to konw how to run the codes to start federated learning?
Thank you very much!

**Comment by LiangzeJiang** [comment]
Hello,

Thank you for your interest in our work.

The reason that only scripts[0] enters is because the [num_jobs_per_node](https://github.com/LINs-lab/FedTHE/blob/9eeff1978e0179b5a8228c6ad3374d75975a19c9/run_exps.py#L103) is set to 1 (see [here](https://github.com/LINs-lab/FedTHE/blob/9eeff1978e0179b5a8228c6ad3374d75975a19c9/parameters.py#L286)). We used it to allow for multiple experiments running in parallel (of course when gpu memory permits). Basically, the process will keep launching experiments until there are `num_jobs_per_node` experiments running in parallel, and launch new ones only upon an experiment is finished. 

In your case, there will be only 1 script/experiment running at a time, so the main process executes `sleep()` to wait until it finishes, then launch the next one. So the FL experiments should already started (it creates another process hold by `tmux` sessions in the background), and you can use commands like `tmux -ls` and `tmux attach` to check. 

Please let us know if you have further questions.
